# Generated by Django 2.1.4 on 2019-10-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='img',
        ),
    ]
