# Generated by Django 2.1.4 on 2019-10-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_good_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='img',
            field=models.ImageField(default=0, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
    ]
